Fix `TypeError: domain.enter is not a function`
An `EventEmitter` subclass must not use the `domain` property. Having a
`domain` present triggers Node's deprecated `domain` error handling
behavior, which, as it's not actually loaded, causes a `TypeError`.

Instead, delegate to a separate `EventEmitter` object, so our
`_OrmScope` can safely keep its `domain` property.

https://github.com/nodejs/node-v0.x-archive/issues/3922